server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称j进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
#          uri: http://localhost:8001
          # 需要注意的是uri的协议lb,表示启用Gateway的负载均衡功能.
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/** # 断言，路径相匹配的进行路由
            # 之后才能访问
            - After=2020-11-20T10:53:41.546+08:00[Asia/Shanghai]
            # 带cookie访问
#            - Cookie=name,ckx
        - id: payment_route2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            Path=/payment/add/** #断言,路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/